apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "redpanda-connect.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redpanda-connect.labels" . | nindent 4 }}
data:
  redpanda-connect.yaml: |
    http:
      enabled: true
      address: 0.0.0.0:4195
      root_path: /benthos
      debug_endpoints: false
      cert_file: ""
      key_file: ""
      cors:
        enabled: false
        allowed_origins: []
      basic_auth:
        enabled: false
        realm: restricted
        username: ""
        password_hash: ""
        algorithm: sha256
        salt: ""

    input:
      label: ""
      kafka:
        addresses:
          - 172.29.164.98:9092
          - 172.29.164.99:9092
          - 172.29.164.100:9092          
        topics:
          - baas_topic
        consumer_group: baas
        start_from_oldest: true
        batching:
          count: 100
          period: 1s

    buffer:
      none: {}

    pipeline:
      threads: 4
    #  processors:
    #    - bloblang: |
    #        root = this


    output:
      label: ""
      #fallback:
      elasticsearch:
        urls:
          - http://192.168.175.85:9200
          - http://192.168.175.86:9200
          - http://192.168.175.87:9200
          - http://192.168.175.88:9200
        index: "logs-generic-kafka-bonsa-log"
        action: "create"
        basic_auth:
          enabled: true
          username: "accountusr"
          password: "HHZmMewPUy8o2retfR"


    input_resources: []
    processor_resources: []
    output_resources: []
    cache_resources: []
    rate_limit_resources: []

    logger:
      level: INFO
      format: logfmt
      add_timestamp: false
      level_name: level
      timestamp_name: time
      message_name: msg
      static_fields:
        '@service': redpanda-connect
      file:
        path: ""
        rotate: false
        rotate_max_age_days: 0

    metrics:
      prometheus: {}
      mapping: ""

    tracer:
      none: {}

    shutdown_delay: 0s
    shutdown_timeout: 20s
    tests: []

    redpanda:
      seed_brokers: []
      client_id: benthos
      tls:
        enabled: false
        skip_cert_verify: false
        enable_renegotiation: false
        root_cas: ""
        root_cas_file: ""
        client_certs: []
      sasl: []
      metadata_max_age: 5m
      pipeline_id: ""
      logs_topic: ""
      logs_level: info
      status_topic: ""
      idempotent_write: true
      timeout: 10s
      max_message_bytes: 1MiB
      broker_write_max_bytes: 100MiB




